version: "3.5"

networks:
  proxy:
    external: true
  default:
    driver: bridge

services:
  sample_es6_resume:
    image: node:11.10-stretch
    container_name: node
    command: "npm run build-prod"
    volumes:
      - './front:/usr/src/app'
    working_dir: '/usr/src/app'
    environment:
      - NODE_ENV=dev
      - PATH=/usr/src/app/node_modules/.bin:$PATH
    labels:
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - default

  nginx_server:
    image: nginx:latest
    container_name: nginx
    volumes:
      - './front/public:/usr/share/nginx/html'
      - './front/dist:/usr/share/nginx/html/dist'
    expose:
      - 80
    command: ['nginx', '-g', 'daemon off;']
    labels:
      - "traefik.frontend.rule=Host:resume.traefik.localhost"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - default